goal_state = {
    (0, 0, 0):{"Left":"R","Up":"Y","Front":"G"},
    (0, 0, 1):{"Left":"R","Up":"Y"},
    (0, 0, 2):{"Left": "R", "Up": "Y", "Back": "B"},
    (0, 1, 0):{"Left": "R", "Front": "G"},
    (0, 1, 1):{"Left": "R"},
    (0, 1, 2):{"Left": "R", "Back": "B"},
    (0, 2, 0):{"Left": "R", "Down": "W", "Front": "G"},
    (0, 2, 1):{"Left": "R", "Down": "W"},
    (0, 2, 2):{"Left": "R", "Down": "W", "Back": "B"},
    (1, 0, 0):{"Up": "Y", "Front": "G"},
    (1, 0, 1):{"Up": "Y"},
    (1, 0, 2):{"Up": "Y", "Back": "B"},
    (1, 1, 0):{"Front": "G"},
    (1, 1, 2):{"Back": "B"},
    (1, 2, 0):{"Down": "W", "Front": "G"},
    (1, 2, 1):{"Down": "W"},
    (1, 2, 2):{"Down": "W", "Back": "B"},
    (2, 0, 0):{"Right": "O", "Up": "Y", "Front": "G"},
    (2, 0, 1):{"Right": "O", "Up": "Y"},
    (2, 0, 2):{"Right": "O", "Up": "Y", "Back": "B"},
    (2, 1, 0):{"Right": "O", "Front": "G"},
    (2, 1, 1):{"Right": "O"},
    (2, 1, 2):{"Right": "O", "Back": "B"},
    (2, 2, 0):{"Right": "O", "Down": "W", "Front": "G"},
    (2, 2, 1):{"Right": "O", "Down": "W"},
    (2, 2, 2):{"Right": "O", "Down": "W", "Back": "B"},
}